[package]
name = "pathfinder"
version = "0.0.0"
authors = ["UAV Austin <uavaustin@gmail.com>"]
license = "MIT"

[badges]
travis-ci = { repository = "uavaustin/pathfinder", branch = "master" }

[dev-dependencies]
rand = "0.5.1"
